name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Skip build on gh-pages
        if: github.ref == 'refs/heads/gh-pages'
        run: echo "Skipping build on gh-pages"

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        if: github.ref != 'refs/heads/gh-pages'
